// chat_raster_test.go — fixture + face pins for the ASCII image lane
// (chat_raster.go): the half-block truecolor rasterizer, the data-URL
// gate (state.ParseDataImageURL/DataURLHash), and the renderConversation
// slot that puts chips + raster rows above a completed boss bubble.
//
// The gold fixture (testdata/checker-8x8.png) is an 8×8 red|blue
// checkerboard, (255,0,0) vs (0,0,255), generated by checkerImage below —
// the test RE-ENCODES the same pixels and asserts the file's bytes match,
// so the gold can never silently drift from the pinned pixel contract.
package panels

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"hash/crc32"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"os"
	"strings"
	"testing"

	"github.com/charmbracelet/x/ansi"

	"github.com/theboringhumane/theboringoffice/internal/state"
)

// checkerImage — the fixture's pixel contract: (x+y)%2==0 → red, else blue.
func checkerImage() *image.NRGBA {
	img := image.NewNRGBA(image.Rect(0, 0, 8, 8))
	red := color.NRGBA{R: 255, G: 0, B: 0, A: 255}
	blue := color.NRGBA{R: 0, G: 0, B: 255, A: 255}
	for y := 0; y < 8; y++ {
		for x := 0; x < 8; x++ {
			if (x+y)%2 == 0 {
				img.SetNRGBA(x, y, red)
			} else {
				img.SetNRGBA(x, y, blue)
			}
		}
	}
	return img
}

func checkerPNG(t *testing.T) []byte {
	t.Helper()
	var b bytes.Buffer
	if err := png.Encode(&b, checkerImage()); err != nil {
		t.Fatalf("encode checker: %v", err)
	}
	return b.Bytes()
}

func loadCheckerFixture(t *testing.T) []byte {
	t.Helper()
	raw, err := os.ReadFile("testdata/checker-8x8.png")
	if err != nil {
		t.Fatalf("gold fixture missing: %v", err)
	}
	return raw
}

// TestCheckerFixtureIsSelfVerifying — the gold file must byte-match a
// fresh encode of checkerImage (the pixel contract never drifts).
func TestCheckerFixtureIsSelfVerifying(t *testing.T) {
	if got, want := loadCheckerFixture(t), checkerPNG(t); !bytes.Equal(got, want) {
		t.Fatalf("testdata/checker-8x8.png drifted from the pixel contract (%d vs %d bytes)", len(got), len(want))
	}
}

// checkerRow — the ONE pinned raster row for the checker at 1:1 scale:
// every row is identical (the parities repeat every 2 pixel rows) and
// every cell re-emits its palette (neighbors never share it).
func checkerRow(top, bot [3]int) string {
	fg := func(c [3]int) string {
		return "\x1b[38;2;" + itoa3(c[0]) + ";" + itoa3(c[1]) + ";" + itoa3(c[2]) + "m"
	}
	bg := func(c [3]int) string {
		return "\x1b[48;2;" + itoa3(c[0]) + ";" + itoa3(c[1]) + ";" + itoa3(c[2]) + "m"
	}
	// x even: fg=topA,bg=botA; x odd: fg=topB,bg=botB (A/B swap each row-pair)
	var b strings.Builder
	for x := 0; x < 8; x++ {
		f, g := top, bot
		if x%2 == 1 {
			f, g = bot, top
		}
		b.WriteString(fg(f) + bg(g) + "▀")
	}
	b.WriteString("\x1b[m")
	return b.String()
}

func itoa3(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [3]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}

var (
	rgbRed  = [3]int{255, 0, 0}
	rgbBlue = [3]int{0, 0, 255}
)

// TestRasterCheckerExactPin — the 8×8 checker at width 8 (1:1 pixels →
// cells) renders EXACTLY 4 half-block rows of the pinned ANSI: fg=top
// pixel, bg=bottom pixel, red|blue alternating, reset trailing. Rows 1-3
// are byte-identical to row 0 (parity repeats every two pixel rows).
func TestRasterCheckerExactPin(t *testing.T) {
	rows, err := RasterFromBytes(loadCheckerFixture(t), 8, 0)
	if err != nil {
		t.Fatalf("rasterize checker: %v", err)
	}
	want := checkerRow(rgbRed, rgbBlue)
	if len(rows) != 4 {
		t.Fatalf("want 4 half-block rows for an 8px-tall image, got %d", len(rows))
	}
	for i, row := range rows {
		if row != want {
			t.Fatalf("row %d mismatch:\n got %q\nwant %q", i, row, want)
		}
	}
}

// TestRasterCheckerWidthCaps — widths ABOVE the source width never invent
// pixels: maxCols 16 and 64 both render the same pinned 8-col frame.
func TestRasterCheckerWidthCaps(t *testing.T) {
	want, err := RasterFromBytes(loadCheckerFixture(t), 8, 8)
	if err != nil {
		t.Fatalf("baseline: %v", err)
	}
	for _, width := range []int{16, 64} {
		got, err := RasterFromBytes(loadCheckerFixture(t), width, width)
		if err != nil {
			t.Fatalf("width %d: %v", width, err)
		}
		if len(got) != len(want) {
			t.Fatalf("width %d: want %d rows, got %d", width, len(want), len(got))
		}
		for i := range got {
			if got[i] != want[i] {
				t.Fatalf("width %d row %d: supersampling invented pixels\n got %q\nwant %q", width, i, got[i], want[i])
			}
		}
	}
}

// TestRasterHalfBlockPairing — a 2×2 RGBA image renders as ONE row with
// the fg=top/bg=bottom contract per cell (red over green, blue over
// black) — exact ANSI pin, no downsample arithmetic involved.
func TestRasterHalfBlockPairing(t *testing.T) {
	img := image.NewNRGBA(image.Rect(0, 0, 2, 2))
	img.SetNRGBA(0, 0, color.NRGBA{R: 255, A: 255}) // top-left red
	img.SetNRGBA(1, 0, color.NRGBA{B: 255, A: 255}) // top-right blue
	img.SetNRGBA(0, 1, color.NRGBA{G: 255, A: 255}) // bottom-left green
	img.SetNRGBA(1, 1, color.NRGBA{A: 255})         // bottom-right black
	var b bytes.Buffer
	if err := png.Encode(&b, img); err != nil {
		t.Fatal(err)
	}
	rows, err := RasterFromBytes(b.Bytes(), 8, 8)
	if err != nil {
		t.Fatalf("rasterize 2x2: %v", err)
	}
	want := "\x1b[38;2;255;0;0m\x1b[48;2;0;255;0m▀" +
		"\x1b[38;2;0;0;255m\x1b[48;2;0;0;0m▀" + "\x1b[m"
	if len(rows) != 1 || rows[0] != want {
		t.Fatalf("2x2 must render ONE pinned half-block row:\n got %q\nwant %q", rows, want)
	}
}

// TestRasterGradientJPEG — a horizontal gradient JPEG rides the JPEG
// decode path: aspect-preserved dims (128×16 at the 64-col cap → 64 cols
// × 4 half-block rows), each row self-contained (reset-tail), 64 cells
// per row, and the box average keeps the row uniform dark→bright.
func TestRasterGradientJPEG(t *testing.T) {
	img := image.NewNRGBA(image.Rect(0, 0, 128, 16))
	for y := 0; y < 16; y++ {
		for x := 0; x < 128; x++ {
			img.SetNRGBA(x, y, color.NRGBA{R: uint8(x * 2), G: uint8(x * 2), B: uint8(x * 2), A: 255})
		}
	}
	var b bytes.Buffer
	if err := jpeg.Encode(&b, img, &jpeg.Options{Quality: 95}); err != nil {
		t.Fatal(err)
	}
	rows, err := RasterFromBytes(b.Bytes(), 64, 20)
	if err != nil {
		t.Fatalf("rasterize gradient jpeg: %v", err)
	}
	if len(rows) > 20 {
		t.Fatalf("row cap: want ≤ 20, got %d", len(rows))
	}
	// 16px tall × 2:1 downsample (128→64 cols) = 8 pixel rows = 4 cells.
	if len(rows) != 4 {
		t.Fatalf("a 128×16 gradient at 64 cols paints 4 half-block rows, got %d", len(rows))
	}
	for i, row := range rows {
		if !strings.HasSuffix(row, "\x1b[m") {
			t.Fatalf("row %d must self-terminate its palette, got %q", i, row[len(row)-8:])
		}
		if strings.Count(row, "▀") != 64 {
			t.Fatalf("row %d: want 64 cells, got %d", i, strings.Count(row, "▀"))
		}
		if !strings.Contains(row, "38;2;") {
			t.Fatalf("row %d carries no truecolor fg", i)
		}
	}
}

// TestRasterGiantDimsRejected — a PNG HEADER claiming 20000×20000 is
// refused from the config read alone (no pixel allocation ever happens):
// the degrade path is the dim chip, never a crash.
func TestRasterGiantDimsRejected(t *testing.T) {
	_, err := RasterFromBytes(pngHeaderWithDims(20000, 20000), 8, 8)
	if err == nil || !strings.Contains(err.Error(), "20000x20000") {
		t.Fatalf("giant dims must reject with the dimension error, got %v", err)
	}
}

// pngHeaderWithDims builds a structurally valid PNG stream with the given
// IHDR dimensions and NO image data — enough for image.DecodeConfig to
// read the header (the rasterizer's header-first guard must trip before
// any allocation).
func pngHeaderWithDims(w, h int) []byte {
	var b bytes.Buffer
	b.Write([]byte{137, 80, 78, 71, 13, 10, 26, 10})
	var ihdr bytes.Buffer
	_ = binary.Write(&ihdr, binary.BigEndian, uint32(w))
	_ = binary.Write(&ihdr, binary.BigEndian, uint32(h))
	ihdr.Write([]byte{8, 6, 0, 0, 0}) // 8-bit RGBA, deflate, no filter, no interlace
	chunk := append([]byte("IHDR"), ihdr.Bytes()...)
	_ = binary.Write(&b, binary.BigEndian, uint32(ihdr.Len()))
	b.Write(chunk)
	_ = binary.Write(&b, binary.BigEndian, crc32.ChecksumIEEE(chunk))
	_ = binary.Write(&b, binary.BigEndian, uint32(0))
	b.WriteString("IEND")
	_ = binary.Write(&b, binary.BigEndian, crc32.ChecksumIEEE([]byte("IEND")))
	return b.Bytes()
}

// TestRasterOversizedRejected — bytes over the 8 MiB cap are refused
// before any decode attempt.
func TestRasterOversizedRejected(t *testing.T) {
	if _, err := RasterFromBytes(make([]byte, state.MediaMaxPayloadBytes+1), 8, 8); err == nil {
		t.Fatal("an over-cap payload must reject")
	}
}

// TestDataURLGate — the wire gate: only data:image/*;base64 payloads;
// text/html never parses, truncated base64 never parses, remote URLs
// never parse, and a real payload round-trips.
func TestDataURLGate(t *testing.T) {
	pngBytes := checkerPNG(t)
	good := "data:image/png;base64," + base64.StdEncoding.EncodeToString(pngBytes)
	mime, raw, err := state.ParseDataImageURL(good)
	if err != nil || mime != "image/png" || !bytes.Equal(raw, pngBytes) {
		t.Fatalf("a valid data URL must round-trip: mime=%q err=%v bytes=%d", mime, err, len(raw))
	}
	for _, bad := range []string{
		"data:text/html;base64,PGI+",
		"data:image/png;base64,A",                                       // truncated base64
		"data:image/png," + base64.StdEncoding.EncodeToString(pngBytes), // not ;base64
		"https://example.com/x.png",
		"",
	} {
		if _, _, err := state.ParseDataImageURL(bad); err == nil {
			t.Fatalf("%q must reject", bad)
		}
	}
	// over-cap payload: a 9 MiB image body base64'd never enters the door.
	big := "data:image/png;base64," + base64.StdEncoding.EncodeToString(make([]byte, state.MediaMaxPayloadBytes+1))
	if _, _, err := state.ParseDataImageURL(big); err == nil {
		t.Fatal("an over-cap data URL must reject")
	}
	// the hash is deterministic + the carrier shape (12 hex chars).
	if h1, h2 := state.DataURLHash(good), state.DataURLHash(good); h1 != h2 || len(h1) != 12 {
		t.Fatalf("DataURLHash must be 12 deterministic hex chars, got %q / %q", h1, h2)
	}
	if state.DataURLHash(good+"x") == state.DataURLHash(good) {
		t.Fatal("different payloads must hash differently")
	}
}

// TestMediaMetaCarrier — the ChatMsg.Meta carrier round-trips (small
// fields only — the URL never rides Meta) and parses false on plain Meta.
func TestMediaMetaCarrier(t *testing.T) {
	items := []state.MediaItem{
		{Mime: "image/png", Filename: "paste-diagram.png", W: 8, H: 8, Hash: "0123abcd4567"},
		{Mime: "image/jpeg", Filename: "photo.jpg", W: 640, H: 480, Hash: ""},
	}
	meta := state.MediaMeta(items)
	if meta == "" || strings.Contains(meta, "data:") || strings.Contains(meta, "http") {
		t.Fatalf("the carrier must stay small (no URLs): %q", meta)
	}
	got, ok := state.ParseMediaMeta(meta)
	if !ok || len(got) != 2 {
		t.Fatalf("carrier round-trip: ok=%v items=%+v", ok, got)
	}
	for i := range items {
		if got[i].Mime != items[i].Mime || got[i].Filename != items[i].Filename ||
			got[i].W != items[i].W || got[i].H != items[i].H || got[i].Hash != items[i].Hash {
			t.Fatalf("item %d mismatch: %+v vs %+v", i, got[i], items[i])
		}
	}
	// non-carriers parse false; the user-attach carrier stays distinct.
	for _, not := range []string{"", "read · src/main.go", state.AttachMeta([]string{"x.png"}), "attach"} {
		if _, ok := state.ParseMediaMeta(not); ok {
			t.Fatalf("%q must NOT parse as the image carrier", not)
		}
	}
}

// TestChatBubbleMediaSlot — the renderConversation slot: a COMPLETED boss
// bubble carrying the meta carrier renders the 🖼 chip ABOVE the body,
// and the pushed raster rows land after it (exactly once) — while a
// PENDING twin bubble renders neither (the pin alone previews).
func TestChatBubbleMediaSlot(t *testing.T) {
	rows, err := RasterFromBytes(loadCheckerFixture(t), 8, 8)
	if err != nil {
		t.Fatalf("rasterize: %v", err)
	}
	if len(rows) == 0 {
		t.Fatal("fixture must rasterize")
	}
	hash := state.DataURLHash("data:image/png;base64,AAAA")
	meta := state.MediaMeta([]state.MediaItem{
		{Mime: "image/png", Filename: "paste-diagram.png", W: 8, H: 8, Hash: hash},
	})
	mk := func() *Chat {
		c := NewChat(nil)
		c.SetSize(80, 30)
		c.SetState(state.OfficeState{Tick: 1, Chat: []state.ChatMsg{
			{ID: "u1", From: "user", Kind: "user", Text: "what does the diagram say?", At: 10},
			{ID: "bossmsg-m1", From: "boss", Kind: "boss", Text: "red squares win, blue loses.", At: 11, Meta: meta},
			{ID: "bossmsg-m2", From: "boss", Kind: "boss", Text: "streaming…", At: 12, Pending: true, Meta: meta},
		}})
		c.SetImageRaster("bossmsg-m1", hash, rows)
		return c
	}
	c := mk()
	convo := c.renderConversation()
	plain := ansi.Strip(convo)
	if !strings.Contains(plain, "🖼 paste-diagram.png · 8×8 · image/png") {
		t.Fatalf("the 🖼 chip must render with dims+mime:\n%s", plain)
	}
	if strings.Count(plain, "🖼 paste-diagram.png") != 1 {
		t.Fatalf("the chip renders EXACTLY once (pending twin never previews):\n%s", plain)
	}
	// raster rows land after the chip and BEFORE the body, exactly once.
	chipIdx := strings.Index(plain, "🖼 paste-diagram.png")
	bodyIdx := strings.Index(plain, "red squares win")
	blockIdx := strings.Index(plain, "▀")
	if blockIdx < 0 || chipIdx < 0 || bodyIdx < 0 || !(chipIdx < blockIdx && blockIdx < bodyIdx) {
		t.Fatalf("order must be chip → raster → body (chip=%d raster=%d body=%d):\n%s", chipIdx, blockIdx, bodyIdx, plain)
	}
	if n := strings.Count(plain, "▀"); n != 32 {
		t.Fatalf("an 8-col × 4-row checker paints 32 half-blocks, got %d", n)
	}
	// the painted rows carry the checker's truecolor palette (raw ANSI).
	if !strings.Contains(convo, "38;2;255;0;0") || !strings.Contains(convo, "48;2;0;0;255") {
		t.Fatalf("the raster must carry the red-over-blue truecolor SGR")
	}
	// the pending twin renders its streaming text UNPACKAGED — no chip,
	// no raster (counts above already prove it; the marker rides along).
	if !strings.Contains(plain, "streaming…") {
		t.Fatalf("the pending bubble's own text must still render:\n%s", plain)
	}
}

// TestChatBubbleMediaOffLane — the chip-only shapes: a failed probe swaps
// the chip copy to the dim unsupported text, and a carrier without any
// pushed raster renders chips alone.
func TestChatBubbleMediaOffLane(t *testing.T) {
	meta := state.MediaMeta([]state.MediaItem{
		{Mime: "image/png", Filename: "paste-diagram.png", W: 8, H: 8, Hash: "aa11bb22cc33"}, // rasterizable, unprobed
		{Mime: "image/png", Filename: "remote.png", W: 0, H: 0},                              // remote/undecodable → unsupported
		{Mime: "image/png", Filename: "broken.png", W: 8, H: 8, Hash: "ff00ff00ff00"},        // probe FAILED → unsupported
	})
	c := NewChat(nil)
	c.SetSize(80, 30)
	c.SetState(state.OfficeState{Tick: 1, Chat: []state.ChatMsg{
		{ID: "bossmsg-m1", From: "boss", Kind: "boss", Text: "three images.", At: 11, Meta: meta},
	}})
	c.SetImageFailed("bossmsg-m1", "ff00ff00ff00")
	plain := ansi.Strip(c.renderConversation())
	if !strings.Contains(plain, "🖼 paste-diagram.png · 8×8 · image/png") {
		t.Fatalf("the unprobed image keeps its normal chip:\n%s", plain)
	}
	if strings.Count(plain, "unsupported image · click txt link") != 2 {
		t.Fatalf("remote + failed both read unsupported:\n%s", plain)
	}
	if strings.Contains(plain, "🖼 remote.png · ") && !strings.Contains(plain, "🖼 remote.png · unsupported") {
		t.Fatalf("a remote (dimless) image must read as unsupported:\n%s", plain)
	}
	if strings.Contains(plain, "▀") {
		t.Fatalf("no raster rows without a landed probe:\n%s", plain)
	}
}
