export const SITE_URL = 'https://boringfloor.com'
export const SITE_NAME = 'theboringfloor'
export const SITE_TAGLINE = 'a virtual office where your agents clock in'
export const GITHUB_REPO = 'https://github.com/theboringhumane/theboringfloor'
export const INSTALL_SH = `${SITE_URL}/install.sh`
export const INSTALL_PS1 = `${SITE_URL}/install.ps1`
export const DISCORD_INVITE = 'https://discord.gg/YPDsHVHTVf'
export const X_URL = 'https://x.com/theboringhumane'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/iamharshdev'
