// Package chatcontext implements the boss-only transcript-context marker
// shared by the OpenCode and Claude backends.
package chatcontext

import (
	"regexp"
	"strconv"
	"strings"
)

const (
	// DefaultCount is used by the marker without a count.
	DefaultCount = 20
	// MaxCount bounds the amount of transcript context an agent can request.
	MaxCount = 50
	// ControlPrefix identifies synthetic recent-message protocol text. It is
	// intentionally shared so transcript consumers do not need to duplicate
	// protocol strings when excluding recovery control rows.
	ControlPrefix = "[theboringfloor] "
	// RecentMessagesRequestedPrefix is the settled bubble for a marker-only
	// request.
	RecentMessagesRequestedPrefix = ControlPrefix + "recent messages requested: "
	// RecentChatContextPrefix begins a synthetic transcript recovery follow-up.
	RecentChatContextPrefix = ControlPrefix + "recent chat context"
	// NoRecentChatContext is sent when no eligible transcript rows exist.
	NoRecentChatContext = ControlPrefix + "no recent chat context available"
	marker              = "⟦recent-messages"
	markerClose         = "⟧"
)

// PromptPreamble is appended after the browser-tool preamble on the first
// boss prompt. It intentionally lives apart from browsertools so that the
// browser preamble's byte contract remains unchanged.
const PromptPreamble = "[theboringoffice harness — recent messages]\n" +
	"If you lose or compact context, you may recover recent office transcript messages sparingly. " +
	"Emit one of these directives on ITS OWN line, at most once per reply:\n" +
	marker + markerClose + " — request the default 20 messages.\n" +
	marker + ": N" + markerClose + " — request N messages (clamped to 1..50).\n" +
	"The office strips the directive from your visible reply. The result arrives as a synthetic follow-up message."

var (
	defaultLineRe = regexp.MustCompile(`(?m)^[ \t]*` + regexp.QuoteMeta(marker+markerClose) + `[ \t]*\r?$\n?`)
	countLineRe   = regexp.MustCompile(`(?m)^[ \t]*` + regexp.QuoteMeta(marker+":") + `[ \t]*([0-9]+)[ \t]*` + regexp.QuoteMeta(markerClose) + `[ \t]*\r?$\n?`)
	blankCollapse = regexp.MustCompile(`\n{3,}`)
)

// Extract removes every valid whole-line recent-messages marker and returns
// the first request only. This preserves the one-request-per-reply contract
// while keeping repeated valid directives out of the persisted transcript.
// Malformed markers and markers embedded in prose are left unchanged.
func Extract(text string) (string, int, bool) {
	type hit struct {
		at    int
		count int
	}
	var hits []hit
	for _, m := range defaultLineRe.FindAllStringIndex(text, -1) {
		hits = append(hits, hit{at: m[0], count: DefaultCount})
	}
	for _, m := range countLineRe.FindAllStringSubmatchIndex(text, -1) {
		hits = append(hits, hit{at: m[0], count: parseCount(text[m[2]:m[3]])})
	}
	if len(hits) == 0 {
		return text, 0, false
	}
	for i := range hits {
		for j := i + 1; j < len(hits); j++ {
			if hits[j].at < hits[i].at {
				hits[i], hits[j] = hits[j], hits[i]
			}
		}
	}
	cleaned := defaultLineRe.ReplaceAllString(text, "")
	cleaned = countLineRe.ReplaceAllString(cleaned, "")
	cleaned = blankCollapse.ReplaceAllString(cleaned, "\n\n")
	return strings.TrimSpace(cleaned), hits[0].count, true
}

func parseCount(raw string) int {
	n, err := strconv.ParseUint(raw, 10, 64)
	if err != nil || n > MaxCount {
		return MaxCount
	}
	if n < 1 {
		return 1
	}
	return int(n)
}

// Scrub extracts one request, emits its count before returning the cleaned
// transcript, and supplies a settled bubble for marker-only replies.
func Scrub(text string, emit func(int)) string {
	cleaned, count, ok := Extract(text)
	if !ok {
		return text
	}
	if emit != nil {
		emit(count)
	}
	if cleaned != "" {
		return cleaned
	}
	return RecentMessagesRequestedPrefix + strconv.Itoa(count)
}

// IsControlText reports whether text is generated by the recent-message
// recovery protocol rather than authored transcript content. Consumers use it
// to prevent a later recovery from recursively returning protocol rows.
func IsControlText(text string) bool {
	text = strings.TrimSpace(text)
	return strings.HasPrefix(text, RecentMessagesRequestedPrefix) ||
		strings.HasPrefix(text, RecentChatContextPrefix) ||
		text == NoRecentChatContext
}
