// thefloor_mcp exposes a running theboringfloor office as an MCP stdio server.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/theboringhumane/theboringfloor/internal/version"
)

func main() {
	versionFlag := flag.Bool("version", false, "print version")
	helpFlag := flag.Bool("help", false, "show help")
	flag.Parse()
	if *versionFlag {
		fmt.Fprintln(os.Stdout, mcpVersionString())
		return
	}
	if *helpFlag {
		fmt.Fprint(os.Stdout, helpText)
		return
	}
	dir, err := projectDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "thefloor_mcp:", err)
		os.Exit(1)
	}
	if err := serve(os.Stdin, os.Stdout, newOffice(dir)); err != nil {
		fmt.Fprintln(os.Stderr, "thefloor_mcp:", err)
		os.Exit(1)
	}
}

func projectDir() (string, error) {
	dir := strings.TrimSpace(os.Getenv("THEFLOOR_PROJECT_DIR"))
	if dir == "" {
		var err error
		dir, err = os.Getwd()
		if err != nil {
			return "", err
		}
	}
	return filepath.Abs(dir)
}

func mcpVersionString() string {
	// Keep release metadata generated by the shared build-time stamp variables.
	return strings.Replace(version.String(), "theboringoffice", "thefloor_mcp", 1)
}

const helpText = `thefloor_mcp — theboringfloor Model Context Protocol server

Serves MCP JSON-RPC 2.0 over stdin/stdout. stdout is reserved for protocol frames.

Tools:
  plan_present        Present a plan draft in a live office.
  plan_update         Update a plan draft in a live office.
  plan_get_approved   Read the approved plan (live, then on-disk snapshot).
  transcript_read     Read the transcript (live, then on-disk snapshot).
  transcript_search   Search the current project's on-disk transcript.
  office_status       Report live or persisted office status.

Environment:
  THEFLOOR_PROJECT_DIR  Project directory (defaults to the current directory).
  THEBORINGOFFICE_HOME  State-home override used to locate control/session files.
`
